version: "3.7"
services:
  
  alerta-db:
    image: mongo:4.4.2
    ports:
        - "27017:27017"
    volumes:
      - dbdata:/data/db
    restart: unless-stopped

  alerta-web:
    image: alerta/alerta-web
    environment:
      - DEBUG=1  # remove this line to turn DEBUG off
      - DATABASE_URL=mongodb://alerta-db:27017/monitoring
      - AUTH_REQUIRED=True
      - AUTH_PROVIDER=basic
      - ADMIN_USERS=admin@alerta.io,devops@alerta.io #default password: alerta
      - ADMIN_KEY=demo-key
      - SECRET_KEY=secret-key
      - PLUGINS=reject,blackout,normalise,enhance
    labels:
      - traefik.enable=true
      - traefik.http.routers.web.entrypoints=websecure
      - traefik.http.routers.web.rule=Host(`alarm.mydomain.com`) # set your domain
      - traefik.http.routers.web.tls.certresolver=myresolver
      - traefik.http.routers.web.tls=true
      - traefik.http.routers.web.service=web-service
      - traefik.http.services.web-service.loadbalancer.server.port=8080
    restart: unless-stopped

  alerta-proxy:
    image: traefik:v2.3
    ports:
      - "80:80"
      - "443:443"
    command: 
      - --api.insecure=false
      - --api.dashboard=false
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.myresolver.acme.httpchallenge=true
      - --certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.myresolver.acme.email=webmaster@mydomain.com # set your email
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    

volumes:
  dbdata:
    driver: local
  letsencrypt:
    driver: local