version: "3.7"
services:
  
  alerta-db:
    image: mongo:4.4.2
    ports:
        - "27017:27017"
    volumes:
      - dbdata:/data/db
    restart: unless-stopped

  alerta-web:
    image: alerta/alerta-web
    environment:
      - DEBUG=1  # remove this line to turn DEBUG off
      - DATABASE_URL=mongodb://alerta-db:27017/monitoring
      - AUTH_REQUIRED=True
      - AUTH_PROVIDER=basic
      - ADMIN_USERS=admin@alerta.io,devops@alerta.io #default password: alerta
      - ADMIN_KEY=demo-key
      - SECRET_KEY=secret-key
      - PLUGINS=reject,blackout,normalise,enhance
    labels:
      - traefik.enable=true
      - traefik.http.routers.web.entrypoints=lb
      - traefik.http.routers.web.rule=Host(`localhost`)
      - traefik.http.routers.web.service=web-service
      - traefik.http.services.web-service.loadbalancer.server.port=8080
    restart: unless-stopped

  alerta-lb:
    image: traefik:v2.3
    ports:
      - "80:80"
    command: 
      - --api.insecure=false
      - --api.dashboard=false
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.lb.address=:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    

volumes:
  dbdata:
      driver: local